version: '3.1'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: 'no'
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: elfys
    ports:
      - '3306:3306'
    volumes:
      - ${LAST_DUMP}:/docker-entrypoint-initdb.d/dump.sql:ro
      - db_data:/var/lib/mysql:rw

volumes:
    db_data: {}
