"""Remove test_structure column from chip table

Revision ID: 0c81034cf2b6
Revises: c166884016e8
Create Date: 2024-05-07 15:40:41.226567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c81034cf2b6'
down_revision = 'c166884016e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chip', 'test_structure')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chip', sa.Column('test_structure', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
