"""instrument name not null

Revision ID: 84438e320041
Revises: 3ed38d7c97c8
Create Date: 2023-05-28 11:09:09.426730

"""
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84438e320041'
down_revision = '3ed38d7c97c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instrument', 'name',
                    existing_type=mysql.VARCHAR(length=100),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instrument', 'name',
                    existing_type=mysql.VARCHAR(length=100),
                    nullable=True)
    # ### end Alembic commands ###
