"""Add Matrix table

Revision ID: c166884016e8
Revises: f440dd8943b7
Create Date: 2024-04-26 08:05:15.507145

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c166884016e8'
down_revision = 'f440dd8943b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'matrix',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=20), nullable=True),
        sa.Column('width', sa.Integer(), nullable=True),
        sa.Column('height', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chip', sa.Column('matrix_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chip_matrix_id'), 'chip', ['matrix_id'], unique=False)
    op.create_foreign_key(
        'chip__matrix',
        'chip',
        'matrix',
        ['matrix_id'],
        ['id'],
        onupdate='CASCADE',
        ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chip__matrix', 'chip', type_='foreignkey')
    op.drop_index(op.f('ix_chip_matrix_id'), table_name='chip')
    op.drop_column('chip', 'matrix_id')
    op.drop_table('matrix')
    # ### end Alembic commands ###
