"""add wafer type column

Revision ID: ea3696fd0d5a
Revises: d9cf1337bbed
Create Date: 2023-02-05 12:57:37.621195

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ea3696fd0d5a"
down_revision = "d9cf1337bbed"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("wafer", sa.Column("type", sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wafer", "type")
    # ### end Alembic commands ###
