name: Linting

on:
  push:

permissions:
  contents: read

jobs:
  flake8:
    name: Lint with flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read Python version from .python-version
        id: read_python_version
        run: echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 .
