name: Quality assurance

on: push

permissions:
  contents: read


jobs:
  qa:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: pwd
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'
          cache: 'pipenv'

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --deploy --dev --system

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Analysing the code with pylint
        run: |
          pylint --rcfile=.pylintrc --ignore=tests analyzer measure
          pylint --rcfile=tests.pylintrc analyzer/tests measure/tests

      - name: Static type checking
        run: pyright

      - name: Run analyzer unit tests
        run: timeout 2m pytest ./analyzer || exit 1

      - name: Run measure unit tests
        run: timeout 1m pytest ./measure || exit 1

      - name: Run ORM unit tests
        run: timeout 1m pytest ./orm || exit 1
