name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New release version'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read Python version from .python-version
        id: read_python_version
        run: echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pipenv'

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --deploy --system

      - name: Set version
        run: echo "VERSION='${{ github.event.inputs.version }}'" > ./version.py

      - name: Build executable
        run: pyinstaller -c -n Analyzer -D analyzer/__main__.py
        id: pyinstaller

      - name: Create Release Artifact
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          path: './dist/Analyzer/*'
          filename: 'analyzer.zip'

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "analyzer.zip"
          tag: v${{ github.event.inputs.version }}
          makeLatest: true
          generateReleaseNotes: true
