name: Static Type Checking

on:
  push:

permissions:
  contents: read

jobs:
  pyright:
    name: Run Pyright for Static Type Checking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read Python version from .python-version
        id: read_python_version
        run: echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pipenv'

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --deploy --dev --system

      - name: Run Pyright
        run: pyright
