name: Unit Tests

on:
  push:

permissions:
  contents: read

jobs:
  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: pwd
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read Python version from .python-version
        id: read_python_version
        run: echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pipenv'

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --deploy --dev --system

      - name: Wait for MySQL service
        run: |
          for i in {1..30}; do
            mysqladmin ping -h 127.0.0.1 --port=3306 --silent && break
            echo "Waiting for MySQL..."
            sleep $i
          done

      - name: Run analyzer unit tests
        run: timeout 2m pytest ./analyzer --db-url='mysql://root:pwd@127.0.0.1:3306/test' || exit 1

      - name: Run measure unit tests
        run: timeout 1m pytest ./measure --db-url='mysql://root:pwd@127.0.0.1:3306/test' || exit 1

      - name: Run ORM unit tests
        run: timeout 1m pytest ./orm --db-url='mysql://root:pwd@127.0.0.1:3306/test' || exit 1
